void pyramid_function(int row, int fill_input, int type_input, char symbol, int position, int outlinecolor, int fillcolor);
void rectangle_function(int row, int col, int fill_input, char symbol, int position, int outlinecolor, int fillcolor);
void line_function(int row, char symbol, int type_input, int position, int color);
void square_function(int row, char symbol, int fill_input, int position, int outlinecolor, int fillcolor);
void alphabet_function(int size, char symbol, char i, int color, int position);
void tripozium_function(int size, char symbol, int type_input, int fill_input, int position, int outlinecolor, int fillcolor);
void paralellogram_function(int size, char symbol, int fill_input, int position, int outlinecolor, int fillcolor);
void hexagon_function(int size, char symbol, int fill_input, int position, int outlinecolor, int fillcolor);
void triangle_function(int size, char symbol, int type_input, int fill_input, int position, int outlinecolor, int fillcolor);
void pentagon_function(int size, int fill_input, int type_input, char symbol, int position, int outlinecolorChoice, int fillcolorChoice);
void arrows_function(int size, int fill_input, int type_input, char symbol, int position, int outlinecolorChoice, int fillcolorChoice);
void stars_function(int size, int fill_input, int type_input, char symbol, int position, int outlinecolorChoice, int fillcolorChoice);
void circle_function(int size, int fill_input, char symbol, int position, int outlinecolorChoice, int fillcolorChoice);
void chatbox_function(int size, int fill_input, char symbol, int position, int outlinecolorChoice, int fillcolorChoice);
void heart_function(int size, int fill_input, char symbol, int position, int outlinecolorChoice, int fillcolorChoice);
void diamond_function(int size, int fill_input, char symbol, int position, int outlinecolorChoice, int fillcolorChoice);
void kite_function(int size, int fill_input, int type_input, char symbol, int position, int outlinecolorChoice, int fillcolorChoice);
void numbers_function(int size, char symbol,int type, int position, int outlinecolorChoice);
void oval_function(int size, int fill_input, char symbol, int position, int outlinecolorChoice, int fillcolorChoice);
void tree_function( int fill_input, char symbol, int position, int outlinecolor, int fillcolor,int n);
void freehand_function(int x, int y);
void hut_function(int size, int outline_color_choice, char character, int position);